Porting to python 3
Prescrypto/RexChain pull request #39
Opened 2019-05-03 15:19 UTC by mevangelista-alvarado

-

2019-05-03 16:42 UTC, xtornasol512 requested changes
Se ve muy bien muy poquitos cambios! Pues ahora te enlistare algunas cosas que debemos checar que funcionen
- Run in Heroku
- Test Payloads
- Test with Wallet works fine!

2019-05-03 16:44 UTC, xtornasol512 commented
El otro comentario es que debio salir ya con linter mike! Pero el del linter ya no recuerdo si hiciste pruebas!, Puedes agregar screenshoots de que un payload se genero correcto en RexChain con el linter, pondre este comment igual en el PR

2019-05-03 17:39 UTC, mevangelista-alvarado commented
> El otro comentario es que debio salir ya con linter mike! Pero el del linter ya no recuerdo si hiciste pruebas!, Puedes agregar screenshoots de que un payload se genero correcto en RexChain con el linter, pondre este comment igual en el PR

@xtornasol512 En el otro [PR 36](https://github.com/Prescrypto/RexChain/pull/36) migre recetas de Prescrypto local apuntando a dicho PR con el comando migrate_2_blockchain.

2019-05-03 17:41 UTC, xtornasol512 commented
@mevangelista-alvarado Muy bien @mevangelista !

2019-05-03 17:42 UTC, xtornasol512 commented
@mevangelista-alvarado Entonces podrias ocupar el mismo metodo para probar este PR no? @mevangelista

2019-05-03 17:44 UTC, mevangelista-alvarado commented
> @xtornasol512 
Prefiero probar en local, tengo la corazonada que van a salir mucho errores XD.

2019-05-07 19:48 UTC, xtornasol512 commented on requirements.txt
> +flake8
Bandit y flake8 se agregan al bin/setup_box mi buen mike! Y aparte bandit no se ha echo aun requisito tenerlo, mejor quitalo o agregalo a travis pero debes resolver cualquier issue que aparezca

2019-05-07 19:48 UTC, xtornasol512 requested changes
Checa el comment mike

2019-05-07 20:29 UTC, mevangelista-alvarado commented on requirements.txt
> +flake8
Listo @xtornasol512

2019-05-07 20:49 UTC, merged